source "https://rubygems.org"

gem "ruby_llm"

# TTY toolkit
gem "tty-reader"
gem "tty-spinner"
gem "tty-table"
gem "tty-box"
gem "tty-markdown"
gem "tty-prompt"
gem "tty-progressbar"
gem "tty-cursor"

# Utilities
gem "pastel"         # Terminal colors
gem "rouge"          # Syntax highlighting

group :test do
  gem "minitest"
  gem "rake"
  gem "webmock"      # HTTP mocking
end
