source "https://rubygems.org"

# TTY toolkit
gem "tty-reader", "~> 0.9"
gem "tty-spinner"
gem "tty-table"
gem "tty-box"
gem "tty-markdown"
gem "tty-prompt"
gem "tty-progressbar"
gem "tty-cursor"

# Utilities
gem "pastel"         # Terminal colors
gem "rouge"          # Syntax highlighting

# HTTP client
gem "faraday", "~> 2.0"
gem "faraday-retry", "~> 2.0"
gem "net-http-persistent", "~> 4.0"

# Circuit breaker
gem "stoplight", "~> 4.0"

# Web server
gem "falcon", "~> 0.47"
gem "async-websocket"

group :test do
  gem "minitest"
  gem "rake"
  gem "webmock"      # HTTP mocking
end
