require "rake/testtask"

Rake::TestTask.new(:test) { |t| t.pattern = "test/test_*.rb" }

desc "Run tests with coverage report"
task :coverage do
  ENV["COVERAGE"] = "true"
  Rake::Task[:test].invoke
end

task default: :test
