#!/usr/bin/env ruby
# frozen_string_literal: true
# Constants for postpro.rb - Master.yml compliance
# Extracted magic numbers for clarity and maintainability

module PostproConstants
  # Color Temperature Ranges (Kelvin)
  TEMP_MIN = 2000
  TEMP_MAX = 12000
  TEMP_NEUTRAL = 5500
  TEMP_WARM = 5200
  TEMP_COOL = 5800
  TEMP_CINEMATIC = 4800
  
  # Highlight Processing
  HIGHLIGHT_THRESHOLD = 200
  HIGHLIGHT_ROLLOFF_FACTOR = 0.3
  HIGHLIGHT_ROLLOFF_POWER = 0.7
  
  # Blur Radii
  BLUR_MICRO_CONTRAST = 5
  BLUR_VINTAGE_GLOW = 20
  BLUR_HALATION_PRIMARY = 20
  BLUR_HALATION_SECONDARY = 40
  BLUR_HALATION_TERTIARY = 80
  BLUR_BLOOM_PRIMARY = 8
  BLUR_BLOOM_SECONDARY = 16
  BLUR_CHEMICAL_VARIANCE = 20
  
  # Skin Protection (HSV)
  SKIN_HUE_MIN = 25.5
  SKIN_HUE_MAX = 63.75
  SKIN_SAT_MIN = 51
  SKIN_SAT_MAX = 153
  SKIN_PROTECT_FACTOR = 0.7
  
  # Grain Parameters
  GRAIN_BASE_ISO = 100.0
  GRAIN_BASE_ISO_DEFAULT = 400
  GRAIN_SHADOW_MULTIPLIER_MIN = 0.4
  GRAIN_SHADOW_MULTIPLIER_MAX = 1.5
  GRAIN_COMPOSITE_OPACITY = 0.25
  
  # Halation
  HALATION_SCATTER_WEIGHT_1 = 0.3
  HALATION_SCATTER_WEIGHT_2 = 0.2
  HALATION_SCATTER_WEIGHT_3 = 0.1
  HALATION_COLOR_R = 255
  HALATION_COLOR_G = 80
  HALATION_COLOR_B = 30
  
  # Color Bleed (per channel blur radii factors)
  COLOR_BLEED_RED = 0.8
  COLOR_BLEED_GREEN = 0.6
  COLOR_BLEED_BLUE = 1.0
  
  # Chemical Variance
  CHEMICAL_VARIANCE_DOWNSAMPLE = 10
  CHEMICAL_VARIANCE_SIGMA = 5
  
  # Chromatic Aberration
  CHROMATIC_ABERRATION_MIN = 0.001
  CHROMATIC_ABERRATION_DEFAULT = 0.002
  
  # Shadow Lift
  SHADOW_LIFT_DEFAULT = 0.15
  SHADOW_LIFT_POWER = 2.0
  SHADOW_LIFT_PRESERVE_FACTOR = 0.8
  
  # Micro Contrast
  MICRO_CONTRAST_RADIUS_DEFAULT = 5
  MICRO_CONTRAST_INTENSITY_DEFAULT = 0.3
  
  # Color Separation Factors
  COLOR_SEP_R_FROM_G = 0.08
  COLOR_SEP_R_FROM_B = 0.05
  COLOR_SEP_G_FROM_R = 0.06
  COLOR_SEP_G_FROM_B = 0.10
  COLOR_SEP_B_FROM_R = 0.04
  COLOR_SEP_B_FROM_G = 0.07
  
  # Teal-Orange Grading
  TEAL_ORANGE_SKIN_PROTECT = 0.8
  TEAL_ORANGE_RED_BOOST = 0.25
  TEAL_ORANGE_RED_LIFT = 8
  TEAL_ORANGE_GREEN_CUT = 0.08
  TEAL_ORANGE_BLUE_BOOST = 0.35
  
  # Bloom Pro
  BLOOM_BRIGHT_MULTIPLIER = 2.0
  BLOOM_SECONDARY_WEIGHT = 0.5
  BLOOM_COMPOSITE_WEIGHT = 0.2
  
  # Performance
  GC_INTERVAL_FILES = 10
  
  # Output
  JPEG_QUALITY_DEFAULT = 95
  VARIATIONS_DEFAULT = 2
  VARIATIONS_MIN = 1
  VARIATIONS_MAX = 5
  
  # Repligen Integration
  REPLIGEN_SCAN_WINDOW_SECONDS = 300
  
  # Random FX
  RANDOM_INTENSITY_MIN_PROFESSIONAL = 0.3
  RANDOM_INTENSITY_MAX_PROFESSIONAL = 0.8
  RANDOM_INTENSITY_MIN_EXPERIMENTAL = 0.5
  RANDOM_INTENSITY_MAX_EXPERIMENTAL = 1.5
  RANDOM_LEAKS_COUNT_MIN = 2
  RANDOM_LEAKS_COUNT_MAX = 5
  RANDOM_FLARE_COUNT_MIN = 3
  RANDOM_FLARE_COUNT_MAX = 6
  RANDOM_FLARE_LENGTH = 200
  
  # Noise
  NOISE_SIGMA_BASE = 25
  NOISE_SIGMA_VHS = 40
  NOISE_SIGMA_GLITCH = 20
  
  # VHS Effect
  VHS_NOISE_OPACITY = 0.4
  VHS_LINES_OPACITY = 0.3
  VHS_LINES_AMPLITUDE = 0.3
  VHS_LINES_OFFSET = 150
  
  # Glitch Effect
  GLITCH_SHIFT_BASE = 15
  GLITCH_NOISE_OPACITY = 0.4
  
  # Vintage Lens
  VINTAGE_ZEISS_RADIUS = 3
  VINTAGE_ZEISS_INTENSITY = 0.4
  VINTAGE_LEICA_GLOW = 0.3
  VINTAGE_HELIOS_BLEND = 0.3
end
